exp:
	  TRUE    |    FALSE    |    STRING    |    UINT8    |    '$' UINT8                 |
	  XCOMMAND '.' EXIT_STATUS                                                          |
	  exp RE_MATCH exp     |     exp RE_NMATCH exp                                      |
	  exp AND exp |  exp OR exp  |  exp EQ exp  |  exp NEQ exp                          |
	  NOT exp     |     '(' exp ')'                                                     ;                                    
exp_list:
	  exp    |    exp_list ',' exp                                                      ;
argv:
	  /*empty*/    |    exp_list                                                        ;
qualification:
	  /*empty*/    |    WHEN  exp                                                       ;
string_list:
	  STRING    |    string_list  ','  STRING                                           ;
command_argv:
	  /*empty*/    |    '(' ')'    |    '(' string_list ')'                             ;
statement:
	  COMMAND NAME command_argv '{' PATH '=' STRING ';' '}'                             |
	  EXEC  XCOMMAND '('  argv  ')'  qualification  ';'                                 ;
statement_list:
	  statement    |    statement_list statement                                        ;
