#!/bin/bash
#
#  Synopsis:
#	Start a present slide show on an http port.
#  Usage:
#	#  public internet
#	./boot-present >boot-present.out 2>&1 &
#
#	#  local dev machine
#	./boot-present 127.0.0.1:8080 >boot-present.out 2>&1 &
#
#	#  private internet for peer review
#	./boot-present 10.0.29.3:8080 >boot-present.out 2>&1 &
#
export GOPATH=/usr/local
HTTP=$1
HTTP=${HTTP:=$(hostname):8080}

PATH=/usr/local/go/bin:.:$PATH
exec present -http=$HTTP -play=true
