#!/usr/bin/env perl
#
#  Synopsis:
#	Implements argument processing for /cgi-bin/pdfbox2.
#  Source Path:
#	lib/pdfbox2.cgi
#  Source SHA1 Digest:
#	No SHA1 Calculated
#  Note:
#	/cgi-bin/pdfbox2 was generated automatically by cgi2perl5.
#
#	Do not make changes directly to this script.
#
die "SERVER_ROOT environment variable not defined"
				unless defined $ENV{SERVER_ROOT};

#
#  Prepend the $SERVER_ROOT/lib directory
#  to the load path.
#
unshift @INC, "$ENV{SERVER_ROOT}/lib";

our (%CGI);

require 'httpd2.d/common.pl';
$CGI{name} = 'pdfbox2';
#
#  Default content type for all elements.
#
$CGI{GET}->{out}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/query-args
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{id} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
$CGI{GET}->{out}->{'query-args'}->{arg}->{class} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
#
#  'out' query argument must match one of the out putter names.
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{out} = {
	perl5_re	=> 	'(?:text[.]count)|(?:input[.]q)|(?:div[.]syn)|help',
	default		=>	'help',
};
#
#  BEGIN: /cgi/GET/out/putter[@name='text.count']
#
$CGI{GET}->{out}->{putter}->{'text.count'}->{name} = 'text.count';
$CGI{GET}->{out}->{putter}->{'text.count'}->{'content-type'} = 'text/plain';

#
#  BEGIN: /cgi/GET/out/putter[@name=text.count]/query-args
#
$CGI{GET}->{out}->{putter}->{'text.count'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{1,256}',
};
#
#  END: /cgi/GET/out/putter[@name=text.count]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='text.count']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='input.q']
#
$CGI{GET}->{out}->{putter}->{'input.q'}->{name} = 'input.q';
$CGI{GET}->{out}->{putter}->{'input.q'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=input.q]/query-args
#
$CGI{GET}->{out}->{putter}->{'input.q'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{1,256}',
};
#
#  END: /cgi/GET/out/putter[@name=input.q]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='input.q']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='div.syn']
#
$CGI{GET}->{out}->{putter}->{'div.syn'}->{name} = 'div.syn';
$CGI{GET}->{out}->{putter}->{'div.syn'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=div.syn]/query-args
#
$CGI{GET}->{out}->{putter}->{'div.syn'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{1,256}',
};
$CGI{GET}->{out}->{putter}->{'div.syn'}->{'query-args'}->{arg}->{pos} = {
	perl5_re	=>	'1|2',
};
#
#  END: /cgi/GET/out/putter[@name=div.syn]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='div.syn']
#

$CGI{GET}->{out}->{putter}->{help}->{name} = 'help';
$CGI{GET}->{out}->{putter}->{help}->{'content-type'} = 'text/html';

require "httpd2.d/$ENV{REQUEST_METHOD}.pl";
